steps:

- name: 'python:2.7'
  args: ['bash', 'docker/run_tests.sh']
  id: py27_without_cython
  waitFor: ['-']
  env:
    - DISABLE_CYTHON=1

- name: 'python:2.7'
  args: ['bash', 'docker/run_tests.sh']
  id: py27_with_cython
  waitFor: ['-']
  env:
    - FORCE_CYTHON=1

- name: 'python:3.4'
  args: ['bash', 'docker/run_tests.sh']
  id: py34_without_cython
  waitFor: ['-']
  env:
  - DISABLE_CYTHON=1
  - PYTHON3=1

- name: 'python:3.4'
  args: ['bash', 'docker/run_tests.sh']
  id: py34_with_cython
  waitFor: ['-']
  env:
  - FORCE_CYTHON=1
  - PYTHON3=1

- name: 'python:3.5'
  args: ['bash', 'docker/run_tests.sh']
  id: py35_without_cython
  waitFor: ['-']
  env:
  - DISABLE_CYTHON=1
  - PYTHON3=1

- name: 'python:3.5'
  args: ['bash', 'docker/run_tests.sh']
  id: py35_with_cython
  waitFor: ['-']
  env:
  - FORCE_CYTHON=1
  - PYTHON3=1

- name: 'python:3.6'
  args: ['bash', 'docker/run_tests.sh']
  id: py36_without_cython
  waitFor: ['-']
  env:
    - DISABLE_CYTHON=1
    - PYTHON3=1

- name: 'python:3.6'
  args: ['bash', 'docker/run_tests.sh']
  waitFor: ['-']
  id: py36_with_cython
  env:
    - FORCE_CYTHON=1
    - PYTHON3=1
